[info]
typeName = "std::set<"
numTemplateParams = 1
ctype = "SET_TYPE"
header = "set"
ns = ["namespace std"]
replaceTemplateParamIndex = [1]
allocatorIndex = 2
# underlyingContainerIndex = 0

[codegen]
decl = """
template <typename DB, typename T0, typename T1, typename T2>
struct TypeHandler<DB, %1% <T0, T1, T2>> {
  using type = StaticTypes::Pair<DB,
      StaticTypes::VarInt<DB>,
      StaticTypes::List<DB, typename TypeHandler<DB, T0>::type>>;

  static StaticTypes::Unit<DB> getSizeType(
      const %1%<T0, T1, T2>& container,
      typename TypeHandler<DB, %1%<T0, T1, T2>>::type returnArg) {
    constexpr size_t nodeSize = sizeof(typename %1%<T0, T1, T2>::node_type);

    auto tail = returnArg.write(nodeSize)
                    .write(container.size());

    // The double ampersand is needed otherwise this loop doesn't work with
    // vector<bool>
    for (auto&& it : container) {
      tail = tail.delegate([&it](auto ret) {
        return OIInternal::getSizeType<DB>(it, ret);
      });
    }

    return tail.finish();
  }
};
"""

func = """
template<typename Key, typename Compare, typename Alloc>
void getSizeType(const %1%<Key, Compare, Alloc> &container, size_t& returnArg)
{
    constexpr size_t nodeSize = sizeof(typename %1%<Key, Compare, Alloc>::node_type);
    size_t numElems = container.size();

    SAVE_SIZE(sizeof(%1%<Key, Compare, Alloc>) + (nodeSize * numElems));

    SAVE_DATA((uintptr_t)nodeSize);
    SAVE_DATA((uintptr_t)numElems);

    // The double ampersand is needed otherwise this loop doesn't work with vector<bool>
    for (auto&& it: container) {
    getSizeType(it, returnArg);
    }
}
"""
