[info]
typeName = "std::unordered_set<"
numTemplateParams = 1
ctype = "UNORDERED_SET_TYPE"
header = "unordered_set"
ns = ["namespace std"]
replaceTemplateParamIndex = [1, 2]
allocatorIndex = 3
# underlyingContainerIndex = 0

[codegen]
decl = """
template <typename DB, typename T0, typename T1, typename T2, typename T3>
struct TypeHandler<DB, %1%<T0, T1, T2, T3>> {
  using type = StaticTypes::Pair<
      DB, StaticTypes::VarInt<DB>,
      StaticTypes::Pair<
          DB, StaticTypes::VarInt<DB>,
          StaticTypes::List<DB, typename TypeHandler<DB, T0>::type>>>;

  static StaticTypes::Unit<DB> getSizeType(
      const %1%<T0, T1, T2, T3>& container,
      typename TypeHandler<DB, %1%<T0, T1, T2, T3>>::type returnArg) {
    constexpr size_t nodeSize = sizeof(typename %1%<T0, T1, T2, T3>::node_type);

    auto tail = returnArg.write(nodeSize)
                    .write(container.bucket_count())
                    .write(container.size());

    // The double ampersand is needed otherwise this loop doesn't work with
    // vector<bool>
    for (auto&& it : container) {
      tail = tail.delegate([&it](auto ret) {
        return OIInternal::getSizeType<DB>(it, ret);
      });
    }

    return tail.finish();
  }
};
"""

func = """
// DummyFunc %1%
"""
