name: facebookexperimental/object-introspection
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: nix fmt
      run: |-
        nix --experimental-features 'nix-command flakes' fmt
        git diff --exit-code
