name: facebookexperimental/object-introspection
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: nix fmt
      run: |-
        nix --experimental-features 'nix-command flakes' fmt
        git diff --exit-code

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm_version: [15]
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: build (LLVM ${{ matrix.llvm_version }})
      run: nix build -L .#oid-llvm${{ matrix.llvm_version }}
