name: facebookexperimental/object-introspection
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: nix fmt
      run: |-
        nix --experimental-features 'nix-command flakes' fmt
        git diff --exit-code

  build-test:
    runs-on: 16-core-ubuntu
    strategy:
      matrix:
        llvm_version: [15]
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: build (LLVM ${{ matrix.llvm_version }})
      # Run the build manually in `nix develop` to keep non-outputs around
      run: |
        nix develop .#oid-llvm${{ matrix.llvm_version }} --command cmake -B build -G Ninja -DFORCE_BOOST_STATIC=Off
        nix develop .#oid-llvm${{ matrix.llvm_version }} --command ninja -C build
    - name: test (LLVM ${{ matrix.llvm_version }})
      env:
        # disable drgn multithreading as tests are already run in parallel
        OMP_NUM_THREADS: 1
      run: |
        nix develop .#oid-llvm${{ matrix.llvm_version }} --command ./tools/config_gen.py -c clang++ build/testing.oid.toml
        nix develop .#oid-llvm${{ matrix.llvm_version }} --command ctest -j --test-dir build/test/
