name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results-15
        name: CTest Tests
        path: results.xml
        reporter: jest-junit
